CREATE TABLE ODNOGRUPNICS (
id INTEGER PRIMARY KEY,
name TEXT NOT NULL,
age INTEGER NOT NULL,
address TEXT NOT NULL
);

INSERT INTO ODNOGRUPNICS VALUES (0001, 'Анна', '18', 'Комарово');
INSERT INTO ODNOGRUPNICS VALUES (0002, 'Борис', '25', 'Москва');
INSERT INTO ODNOGRUPNICS VALUES (0003, 'Василий', '30', 'Уфа');
INSERT INTO ODNOGRUPNICS VALUES (0004, 'Григорий', '31', 'Стамбул');
INSERT INTO ODNOGRUPNICS VALUES (0005, 'Даша', '29', 'Москва');
INSERT INTO ODNOGRUPNICS VALUES (0006, 'Евгений', '19', 'Москва');
INSERT INTO ODNOGRUPNICS VALUES (0007, 'Ёрик бедный', '29', 'Москва');
INSERT INTO ODNOGRUPNICS VALUES (0008, 'Жасмин', '30', 'Саратов');
INSERT INTO ODNOGRUPNICS VALUES (0009, 'Заза', '21', 'Владивосток');
INSERT INTO ODNOGRUPNICS VALUES (0010, 'Константин', '24', 'Москва');
INSERT INTO ODNOGRUPNICS VALUES (0011, 'Людочка', '14', 'Москва');
INSERT INTO ODNOGRUPNICS VALUES (0012, 'Маша', '15', 'Москва');
INSERT INTO ODNOGRUPNICS VALUES (0013, 'Нинель', '23', 'Тула');
INSERT INTO ODNOGRUPNICS VALUES (0014, 'Опунция', '35', 'Пенза');
INSERT INTO ODNOGRUPNICS VALUES (0015, 'Павел', '39', 'Москва');

SELECT * FROM ODNOGRUPNICS WHERE (age>17) & (age<31) & (address='Москва')
